-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgqdjsGTem8dbZSGOP
IPMu8mmgeur0rISMA/xtEFuIsyqgCgYIKoZIzj0DAQehRANCAASxzbhr7GHl5TWd
gKAJpEQ3O7FEWKcCF17VwNLRIqIK3Pta1dAeIzgRrci7WUAmPcVMBkOfZkCnQ6eD
/ZW65uLN
-----END PRIVATE KEY-----